### ISSUE TITLE
Django 1.4 isn't supported, opposite to what the README says

### ISSUE THREAD

**Issue by jjdelc** [django-haystack/celery-haystack#48] opened 2015-09-01 07:08 UTC
I have a legacy project running on Django 1.4.22 and tried to plug celery-haystack to it.

The Celery worker won't start failing with:
`from django.db.transaction import get_connection, atomic`

Which is not added until Django 1.6.

**Comment by nicholasserra** [comment] 2015-09-21 20:15
Just opened a dupe issue on this, with full traceback, didn't notice this until now. Looks like the issue is rooted in django-celery-transactions, which appears to be abandoned.

**Comment by stefanw** [comment] 2018-02-28 13:32
Closing this as Django 1.4 is EOL.

**Closed by stefanw** 2018-02-28 13:32 UTC
