### ISSUE TITLE
Release 0.8.0 broken

### ISSUE THREAD

**Issue by ddemid** [django-haystack/celery-haystack#41] opened 2015-03-25 10:58 UTC
Hey,

It looks like the release 0.8.0 is using wrong task execution which is already fixed in master.

get_update_task method should return instance of task, not class.

**Comment by ddemid** [comment] 2015-03-25 11:01
Sorry, not master.

Here https://github.com/django-haystack/celery-haystack/commit/221bd9d88e7321076fd14c27dac63942a218e1a7

**Comment by ddemid** [comment] 2015-03-27 13:03
Not true.
I've been using a fork of django-celery-transaction which had this issue.

**Comment by ddemid** [comment] 2015-03-27 13:48
No, problem persists. 
Celery "dirty" supports classmethod execution. django-celery-transaction - not.
Class should be instantiated.

**Comment by martey** [comment] 2015-04-01 03:08
This looks like a duplicate of issue #36. Since it's already fixed (and the changelog has been updated), I think the developers are aware that 0.8.0 is not working.

**Comment by nickcatal** [comment] 2015-06-07 23:04
@jezdez it looks like a big issue in 0.8.0 was fixed in 221bd9d88e7321076fd14c27dac63942a218e1a7 , can you release 0.8.1 to pypi?

**Comment by stefanw** [comment] 2015-06-14 08:35
v0.9 has been released.

**Closed by stefanw** 2015-06-14 08:35 UTC
